version:  '3.8'

services:
  mongodb:
    image: mongo:8.0.8
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/db/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - ./videos:/videos
